version: '3.8'

services:
  # React web app service
  pweb-front:
    image: gitlab.cs.pub.ro:5050/bogdan_andrei.buga/war-help/client
    build: ./client # TODO: build: context: ./client
    ports:
      - 3006:3006
    depends_on:
      - pweb-api
    links:
      - pweb-api
    networks:
      - pweb-net

  # ExpressJS API service
  pweb-api:
    image: gitlab.cs.pub.ro:5050/bogdan_andrei.buga/war-help/server
    build: ./server # TODO: build: context: ./server
    ports:
      - 8091:8091
    networks:
      - pweb-net
      - monitoring
    depends_on:
      - mongo
    links:
      - mongo

  # MongoDB service
  mongo:
    image: mongo:4.4.14
    ports:
      - 27017:27017
    restart: always
    environment:
        MONGO_INITDB_DATABASE: pweb
    networks:
      - pweb-net
    volumes:
      - ./server/mongo_db:/data/db
      - ./server/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

  # Nginx revese proxy service 
  proxy:
    image: proxy
    ports:
      - 3050:80
    restart: always
    build: ./server/nginx
    volumes:
      - ./server/data:/data
      - /server/letsencrypt:/etc/letsencrypt
    environment:
      MONGO_INITDB_DATABASE: pweb
    networks:
      - pweb-net
    depends_on:
      - pweb-front
      - pweb-api
      - mongo
      - portainer
      - grafana
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

  # Poratiner service
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./server/portainer-data:/data
    networks:
      - pweb-net
    ports:
      - 9000:9000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  
  # Prometheus service
  prometheus:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./server/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring

  # Grafana service
  grafana:
    image: grafana/grafana:7.1.5
    volumes:
      - grafana_data:/var/lib/grafana
      - ./server/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    networks:
      - monitoring
    deploy:
      placement:
        constraints: [node.role == manager]

  # Node exporter service
  node_exporter:
      image: prom/node-exporter
      deploy:
          mode: global
      volumes:
          - /proc:/host/proc:ro
          - /sys:/host/sys:ro
          - /:/rootfs:ro
      command:
          - '--path.procfs=/host/proc'
          - '--path.rootfs=/rootfs'
          - '--path.sysfs=/host/sys'
          - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      ports:
          - 9100:9100
      networks:
          - monitoring

  rabbitmq:
      image: rabbitmq:3-management
      ports:
          - 5672:5672
          - 15672:15672

volumes:
  mongo_db: {}
  prometheus_data: {}
  grafana_data: {}

networks:
  pweb-net:
    name: pweb-net
  monitoring:
    name: monitoring
