version: '3'

services:
  # ExpressJS Api service
  api:
    build: . # TODO: build: context: ./server
    ports:
      - 5000:5000
    container_name: pweb-api
    networks:
      - pweb-net
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo:4.4.14
    ports:
      - 27017:27017
    container_name: mongo
    restart: always
    environment:
        MONGO_INITDB_DATABASE: pweb
    networks:
      - pweb-net
    volumes:
      - ./mongo_db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
        MONGO_INITDB_DATABASE: pweb
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - pweb-net
      
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
       
volumes:
  mongo_db: {}

networks:
  pweb-net:
    driver: bridge