version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:4.4.14
    restart: always
    volumes:
      - ./mongo_db:/data/db

  # ExpressJS Api service
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo_db:27017/pweb
      DB_NAME: my_db
      NAME: API_Config
    depends_on:
      - mongo_db
      
  proxy:
      build:
        context: .
        dockerfile: Dockerfile.nginx
      image: nginx_proxy:v1
      ports:
        - 80:80
      depends_on:
        - nodeapp
      deploy:
        placement:
          constraints: [node.role == manager]
      depends_on:
        - api
        
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
      
  
volumes:
  mongo_db: {}
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
